# Dataset parameters
dataset: MNIST

# Queue parameters
train_queue_size: 50
test_queue_size: 5

# Training parameters
batch_size: 4
optimizer: adam # Desired optimizer - must exist in build_graph()
learning_rate: 0.0001
total_steps: 250000 # Desired number of iterations - should be done smarter

# Model parameters
model_name: BasicModel
sampler_class: DataSampler
global_sampler: {name: Sequential, params: { max_consecutive_frames: 10,
                                            cache_frames: True,
                                            keep_video_file_open: True }}
