# Dataset parameters
dataset: omniglot
root_dir: './datasets'

# Queue parameters
train_queue_size: 50
test_queue_size: 5

# Meta-learning parameters
num_shot: 5
num_query_imgs: 19

# Training parameters
batch_size: 4
optimizer: adam # Desired optimizer - must exist in build_graph()
learning_rate: 0.0001
total_steps: 250000 # Desired number of iterations - should be done smarter

# Model parameters
model_name: BasicModel
