# Dataset parameters
dataset: cifar100
root_dir: './datasets'

num_way: 50
num_shot: 5
target_num_way: 60

# Training parameters
optimizer: adam # Desired optimizer - must exist in build_graph()
learning_rate: 0.001
total_steps: 39999

# Model parameters
model_name: ExtendModel
